variables:
  BINARY_ARTIFACT_NAME: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  CONTAINER_IMAGE_FULL: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID

stages:
  - build
  - test
  - deploy

# Build image
Build:
  stage: build
  image: docker:stable
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_IMAGE || true
    - docker build --cache-from $CONTAINER_IMAGE -t $CONTAINER_IMAGE .
    - docker tag $CONTAINER_IMAGE $CONTAINER_IMAGE_FULL
    - docker push $CONTAINER_IMAGE
    - docker push $CONTAINER_IMAGE_FULL

Unit:
  stage: test
  image:
    name: $CONTAINER_IMAGE_FULL
    entrypoint: [""]
  script:
    - go get -u github.com/jstemmer/go-junit-report
    - export PATH=$GOPATH/bin:$PATH
    - go test $(go list ./... | grep -v /vendor/) -v | go-junit-report | tee report.xml
  artifacts:
    reports:
      junit: report.xml

Coverage:
  stage: test
  image:
    name: $CONTAINER_IMAGE_FULL
    entrypoint: [""]
  script:
    - go test $(go list ./... | grep -v /vendor/) -bench=. -v -coverprofile coverage.cov

Stage:
  stage: deploy
  image: registry.tubecorporate.com/push/push-infra:latest
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  before_script:
    - mkdir -p -m 700 $HOME/.ssh
    - echo "$SSH_IDENTITY" | base64 -d > $HOME/.ssh/id_rsa
    - chmod 600 $HOME/.ssh/id_rsa
    - cd /root/ansible
  when: manual
  environment:
    name: production
  script:
    - ansible-playbook -i static_inventory/hetzner kafka.yml -e "run_hosts=kafka-hz*" -l "kafka-hz-0" -e "tag=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID" -t kafka-producer

Production:
  stage: deploy
  image: registry.tubecorporate.com/push/push-infra:latest
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  before_script:
    - mkdir -p -m 700 $HOME/.ssh
    - echo "$SSH_IDENTITY" | base64 -d > $HOME/.ssh/id_rsa
    - chmod 600 $HOME/.ssh/id_rsa
    - cd /root/ansible
  when: manual
  environment:
    name: production
  script:
    - ansible-playbook -i static_inventory/hetzner kafka.yml -e "run_hosts=kafka-hz*" -l "!kafka-hz-0" -e "tag=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID" -t kafka-producer
